spring.application.name=Announcement

spring.datasource.url=jdbc:mariadb://localhost:3307/anno?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qwer1234
#spring.jpa.hibernate.ddl-auto=update

file.upload-dir=G:\\code\\Announcement\\Announcement\\uploads

