spring.application.name=Announcement

spring.datasource.url=jdbc:mariadb://mariadb:3306/webdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=web
spring.datasource.password=web123456
spring.jpa.hibernate.ddl-auto=update

file.upload-dir=/app/upload

